public enum TipoTransacao {
    DEPOSITO,
    SAQUE,
    TRANSFERENCIA_ENVIADA,
    TRANSFERENCIA_RECEBIDA,
    PAGAMENTO_EMPRESTIMO,
    APLICACAO_INVESTIMENTO,
    RESGATE_INVESTIMENTO,
    COBRANCA_TARIFA,
    RENDIMENTO_POUPANCA
}